theme: jekyll-theme-minimal
title: Club Omnisport Populaire Brestois (COPB)
description: 'Ensemble d’informations concernant l'association, ainsi que les trois sections qui la composent : plongée, voile et escalade.'
